let randomNumber = Math.floor(Math.random()*10+1); // assigns a value between 1 and 10
let prediction = window.prompt("I'm thinking of a number between 1 and 10. What is it?"); // the user's prediction
prediction = parseInt(prediction);
let exitVariable = true;
let count = 1;

while (exitVariable) {
    if(prediction === randomNumber){
        exitVariable = false; //should exit the loop when the user predicts the same number that was generated by the computer, but it doesn't;
        window.alert("That's Correct! I was thinking" + randomNumber + ".")
    } if (prediction !== randomNumber && (count<=3)){
        prediction = window.prompt("I was not thinking " + prediction + ". Guess again.");
        count++;

    } else window.alert("Sorry you lost you chance")
}

